// https://docusaurus.io/docs/sidebar
module.exports = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Developer API',
      collapsed: true,
      items: [
        'api/introduction',
        'api/authentication',
        'api/pagination',
        'api/versioning',
        'api/errors',
        'api/request-limits',
        'api/date-timezone',
        {
          type: 'category',
          label: 'Resources',
          collapsed: true,
          items: [
            'api/resource/record',
            {
              type: 'category',
              label: 'Field Value',
              collapsed: true,
              items: [
                'api/resource/field-value/overview',
                'api/resource/field-value/text',
                'api/resource/field-value/status',
                'api/resource/field-value/user',
                'api/resource/field-value/category',
                'api/resource/field-value/date',
                'api/resource/field-value/relation',
                'api/resource/field-value/attachment',
                'api/resource/field-value/image',
                'api/resource/field-value/checklist',
                'api/resource/field-value/number',
                'api/resource/field-value/link',
                'api/resource/field-value/calculation',
                'api/resource/field-value/location',
                'api/resource/field-value/email',
                'api/resource/field-value/phone',
              ],
            },
            'api/resource/record-comment',
            'api/resource/record-revision',
            'api/resource/record-permissions',
            'api/resource/record-follow',
            'api/resource/app',
            {
              type: 'category',
              label: 'Field',
              collapsed: true,
              items: [
                'api/resource/field/overview',
                'api/resource/field/text',
                'api/resource/field/user',
                'api/resource/field/category',
                'api/resource/field/status',
                'api/resource/field/relation',
                'api/resource/field/attachment',
                'api/resource/field/image',
                'api/resource/field/date',
                'api/resource/field/location',
                'api/resource/field/email',
                'api/resource/field/phone',
                'api/resource/field/number',
                'api/resource/field/link',
                'api/resource/field/checklist',
                'api/resource/field/unique-id',
                'api/resource/field/calculation',
                'api/resource/field/missing-types',
              ],
            },
            'api/resource/workspace',
            'api/resource/organization',
            'api/resource/user',
            {
              type: 'category',
              label: 'Automation',
              collapsed: true,
              items: [
                'api/resource/automation/overview',
                'api/resource/automation/quickstart',
                'api/resource/automation/discovery',
                'api/resource/automation/manage',
                'api/resource/automation/revisions',
                'api/resource/automation/execution',
                'api/resource/automation/advanced',
                'api/resource/automation/dynamic-values',
                'api/resource/automation/action-examples',
                {
                  type: 'category',
                  label: 'Reference',
                  collapsed: true,
                  items: [
                    'api/resource/automation/reference/object',
                    'api/resource/automation/reference/triggers',
                    'api/resource/automation/reference/filters',
                    {
                      type: 'category',
                      label: 'Actions',
                      collapsed: true,
                      link: { type: 'doc', id: 'api/resource/automation/reference/actions' },
                      items: [
                        'api/resource/automation/reference/actions/custom-code',
                        'api/resource/automation/reference/actions/custom-variable',
                        'api/resource/automation/reference/actions/record-create',
                        'api/resource/automation/reference/actions/current-record-update',
                        'api/resource/automation/reference/actions/current-record-delete',
                        'api/resource/automation/reference/actions/current-record-restore',
                        'api/resource/automation/reference/actions/current-record-get-previous-revision',
                        'api/resource/automation/reference/actions/current-record-comment-create',
                        'api/resource/automation/reference/actions/current-record-comment-or-reply-reply-create',
                        'api/resource/automation/reference/actions/current-record-comment-or-reply-delete',
                        'api/resource/automation/reference/actions/collect-app-records',
                        'api/resource/automation/reference/actions/collect-app-view-records',
                        'api/resource/automation/reference/actions/collect-referenced-records',
                        'api/resource/automation/reference/actions/collected-records-collect-referenced-records',
                        'api/resource/automation/reference/actions/filter-record-collection',
                        'api/resource/automation/reference/actions/sort-record-collection',
                        'api/resource/automation/reference/actions/clear-record-collection',
                        'api/resource/automation/reference/actions/collected-records-update',
                        'api/resource/automation/reference/actions/referenced-records-update',
                        'api/resource/automation/reference/actions/collected-records-comment-create',
                        'api/resource/automation/reference/actions/rollup-iterable-values',
                        'api/resource/automation/reference/actions/current-record-call-automation',
                        'api/resource/automation/reference/actions/collected-records-call-automation',
                        'api/resource/automation/reference/actions/current-record-generate-automation-weblink',
                        'api/resource/automation/reference/actions/display-webpage',
                        'api/resource/automation/reference/actions/redirect-user',
                        'api/resource/automation/reference/actions/send-email',
                        'api/resource/automation/reference/actions/collected-records-send-email',
                        'api/resource/automation/reference/actions/create-pdf',
                        'api/resource/automation/reference/actions/http-call',
                        'api/resource/automation/reference/actions/authenticated-http-call',
                        'api/resource/automation/reference/actions/delay',
                        'api/resource/automation/reference/actions/exit',
                        'api/resource/automation/reference/actions/for-loop',
                        'api/resource/automation/reference/actions/conditional',
                      ],
                    },
                    'api/resource/automation/reference/errors',
                  ],
                },
              ],
            },
            'api/resource/automation-run',
            'api/resource/automation-usage-report',
            'api/resource/file',
            'api/resource/icon',
            'api/resource/link-preview',
            'api/resource/webhook',
            'api/resource/email',
            'api/resource/filter',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Calculation Field',
      collapsed: true,
      items: [
        'calculation/introduction',
        'calculation/editors',
        'calculation/libraries',
        'calculation/markdown',
        'calculation/html',
        {
          type: 'category',
          label: 'Components',
          collapsed: false,
          items: ['calculation/component/link', 'calculation/component/button', 'calculation/component/collapsible'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Automations',
      collapsed: true,
      items: [
        'automations/introduction',
        'automations/code-editor',
        'automations/execution-types',
        'automations/libraries',
        'automations/date-timezone',
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsed: true,
          items: [
            'automations/troubleshooting/filter-values',
            'automations/troubleshooting/ip-addresses',
            'automations/troubleshooting/automations-troubleshooting-errors',
          ],
        },
        'automations/limitations',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Forms',
    //   collapsed: true,
    //   items: ['forms/custom-css'],
    // },
    'contribute',
    {
      type: 'link',
      label: 'Roadmap',
      href: 'https://get.tapeapp.com/roadmap/',
    },
  ],
  guidesSidebar: [
    {
      type: 'category',
      label: 'Developer API',
      collapsed: false,
      items: ['guide/api/getting-started'],
    },
    {
      type: 'category',
      label: 'Automations',
      collapsed: false,
      items: [
        'guide/automations/automation-showcase',
        'guide/automations/convert-pdf-to-text',
        'guide/automations/save-google-form-responses-to-tape',
        'guide/automations/save-jotform-responses-to-tape',
      ],
    },
    'contribute',
    {
      type: 'link',
      label: 'Roadmap',
      href: 'https://get.tapeapp.com/roadmap/',
    },
  ],
};
